version: '3.4'
services:
  api:
    build: .
    ports:
      - "8000:8000"

  librarydb:
    image: "postgres:13.3-alpine"
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=librarydb
